### ISSUE TITLE
Tests fail with the latest resin-request from master

### ISSUE THREAD

**Issue by emirotin** [balena-io-modules/balena-pine#22]
This means even without my latest changes.
This is because the `baseUrl` is not being passed to the request module from the `resin-pine`.
I'll fix it during my work on browser-compat.

**Comment by pimterry** [comment]
Tests are now passing, so I think this is fixed @emirotin?

**Comment by emirotin** [comment]
I seem them failing in the AppVeyor

**Comment by emirotin** [comment]
But it's a different issue now, I think I've fixed this one in the previous PR.
